# Generated by Django 5.1.4 on 2025-03-11 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 8, 44, 28, 816456)),
        ),
    ]
