# Generated by Django 4.2.4 on 2024-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_rename_loans_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
