# Generated by Django 5.1.4 on 2025-03-11 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_alter_repaymentschedule_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 12, 30, 55, 370929)),
        ),
    ]
