# Generated by Django 5.1.4 on 2025-03-11 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_alter_repaymentschedule_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentschedule',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 13, 4, 1, 846650)),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 13, 4, 1, 846578)),
        ),
    ]
