# Generated by Django 5.1.4 on 2025-03-11 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_repaymentschedule_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 13, 4, 39, 712890)),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 13, 4, 39, 712972)),
        ),
    ]
