# Generated by Django 5.1.4 on 2025-03-11 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0005_alter_repaymentschedule_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 13, 39, 39, 652262)),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 13, 39, 39, 652335)),
        ),
    ]
