# Generated by Django 5.1.4 on 2025-03-11 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_alter_repaymentschedule_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 14, 1, 24, 132028)),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 14, 1, 24, 132099)),
        ),
    ]
