# Generated by Django 5.1.4 on 2025-03-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_alter_repaymentschedule_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
