# Generated by Django 5.1.4 on 2025-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_alter_repaymentschedule_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
