# Generated by Django 5.1.4 on 2025-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0009_alter_repaymentschedule_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
