# Generated by Django 5.1.4 on 2025-03-11 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_alter_loan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 21, 1, 8, 533998, tzinfo=datetime.timezone.utc)),
        ),
    ]
