# Generated by Django 5.1.4 on 2025-03-11 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0011_alter_repaymentschedule_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 21, 29, 41, 727646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='expiry_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
