# Generated by Django 5.1.8 on 2025-09-02 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0013_alter_repaymentschedule_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 2, 13, 39, 40, 835516, tzinfo=datetime.timezone.utc)),
        ),
    ]
